### ISSUE TITLE
Possibility to disable coverage with options

### ISSUE THREAD

**Issue by scaytrase** [vipsoft/code-coverage-extension#22]
As soon as there is no documentation, I have a question.

Is it possible to disable extension for certain runs (as for phpunit - just not  specifying coverage options at command line leads to no coverage generated and quicker runs).

I wan't to disable coverage report generation for commit-hooks builds, which were significantly slowed by coverage generation and leave it enabled for all other test-runs. Is it possible without splitting configuration files?

**Comment by robocoder** [comment]
You can configure the coverage options under a different behat profile. The documented example uses the default profile.

https://github.com/vipsoft/code-coverage-extension/blob/master/doc/index.rst
