### ISSUE TITLE
Outdated / Maintenance?

### ISSUE THREAD

**Issue by ek9** [vipsoft/code-coverage-extension#26]
Hi,

I am wondering if there is a plan to still maintain this? At this point I would like to make a lot of changes to the project and have this compatible with latest Symfony components and I am considering a fork, as I see this repo's activity is close to non-existant.

Perhaps any of the contributors or maintainers are still active and would like to give their input, should I try to send some PRs in or rather just fork it to not bother you, if you do not have time for maintenance, as I would like to have a working extension in order.

**Comment by robocoder** [comment]
Correct, I'm not actively updating this ... largely due to the glacial pace at which we update the 3rd party dependencies used by our applications.

Please free to fork and publish package under your own vendor namespace.

**Comment by ek9** [comment]
We have made a fork which we plan to maintain https://github.com/leanphp/behat-code-coverage
We've left the attribution/copyleft in LICENSE files and README, if you notice any problems please do not hesitate to contact us. We have backported latest `2.5.*` version and will release `3.0` once everything is verified and updated. Thank you for the great project again.
