### ISSUE TITLE
Can we use this extension for getting code coverage for behat tests for my drupal application?

### ISSUE THREAD

**Issue by InfobyteTarun** [vipsoft/code-coverage-extension#28]
Hi,

I am using behat for automation testing of our Drupal Web Project.

I am using this library: https://packagist.org/packages/leanphp/behat-code-coverage (Version-3.2.1) for code coverage. However I could able to setup all and it is generating code coverage report as well. But the report is completely blank.

Can I use this extension to achieve the same.

Thanks in advance!

**Comment by robocoder** [comment]
@InfobyteTarun That package is a fork of this repo (which I'm not currently maintaining). Please follow-up with @ek9 at https://github.com/leanphp/behat-code-coverage/issues
